fix postinst/postrm for wheezy.

diff --git a/kippo-0.8/DEBIAN/postrm b/kippo-0.8/DEBIAN/postrm
--- a/kippo-0.8/DEBIAN/postrm
+++ b/kippo-0.8/DEBIAN/postrm
@@ -6,7 +6,7 @@ case "$1" in
         # Remove Kippo data
         rm -rf /var/lib/kippo
 	rm -rf /etc/kippo
-	rm -f /usr/lib/python2.6/dist-packages/kippo
+	rm -f /usr/lib/python2.7/dist-packages/kippo
 	rm -rf /var/run/kippo
 	rm -rf /var/log/kippo
 
@@ -20,7 +20,7 @@ case "$1" in
         if which deluser >/dev/null 2>&1 ; then
             deluser --quiet --system kippo > /dev/null || true
         else
-            echo >&2 "not removing aegir system account because deluser command was not found"
+            echo >&2 "not removing kippo system account because deluser command was not found"
         fi
 
 	# De-register the init script from update-rc.d
@@ -29,7 +29,7 @@ case "$1" in
     remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
 
         # Remove the link to the python modules
-        rm -f /usr/lib/python2.6/dist-packages/kippo
+        rm -f /usr/lib/python2.7/dist-packages/kippo
 
     ;;
 
